sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kyruel/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kyruel/react-test npm test

after_success:
  - docker build -t kyruel/multi-client ./client
  - docker build -t kyruel/multi-nginx ./nginx
  - docker build -t kyruel/multi-server ./server
  - docker build -t kyruel/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kyruel/multi-client
  - docker push kyruel/multi-nginx
  - docker push kyruel/multi-server
  - docker push kyruel/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-1-999040439018
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY